# Generated by Django 4.2.11 on 2024-05-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('avatar', models.CharField(default='/images/typescript.svg', max_length=256, verbose_name='avatar')),
                ('bio', models.TextField(default='', verbose_name='bio')),
                ('birthday', models.CharField(default='', max_length=64, verbose_name='birthday')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='e-mail')),
                ('job', models.CharField(default='', max_length=256, verbose_name='job')),
                ('nickname', models.CharField(max_length=64, verbose_name='nickname')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='phone')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update at')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('gender', models.SmallIntegerField(choices=[(-1, 'Secret'), (0, 'Female'), (1, 'Male')], default=-1, verbose_name='gender')),
            ],
            options={
                'indexes': [models.Index(fields=['username', '-create_at'], name='api_user_usernam_060f29_idx')],
            },
        ),
    ]
