# Generated by Django 4.2.11 on 2024-05-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_topic_favorote_topic_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='topic_tag', to='api.tag'),
        ),
    ]
