# Generated by Django 4.2.11 on 2024-05-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_topic_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='topic_tags', to='api.tag'),
        ),
    ]
