# Generated by Django 4.2.11 on 2024-05-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('content', models.TextField(verbose_name='content')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('tag', models.CharField(max_length=128, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('content', models.TextField(verbose_name='content')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('favorote', models.IntegerField(default=0, verbose_name='favorote')),
                ('title', models.TextField(verbose_name='title')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update at')),
                ('tags', models.ManyToManyField(blank=True, related_name='topic_tags', to='api.tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag', '-create_at'], name='api_tag_tag_268f1a_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='user_favorites', to='api.topic'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-create_at'], name='api_topic_create__521c05_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-create_at'], name='api_comment_create__b802de_idx'),
        ),
    ]
