# Generated by Django 4.2.11 on 2024-05-31 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_topic_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite',
            new_name='favorites',
        ),
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.topic'),
        ),
    ]
