# Generated by Django 4.2.11 on 2024-05-31 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_favorite_user_favorites_alter_comment_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
